---
version: '3.2'
services:
#https://github.com/qdm12/gluetun/wiki/Mullvad
#https://www.youtube.com/watch?v=mH7J_2JKNK0
  syncthing:
    image: lscr.io/linuxserver/syncthing
    container_name: syncthing
    #hostname: syncthing #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /opt/appdata/config:/config
      - /mnt/storage/nextcloud:/nextcloud
      - /mnt/storage/misc/workout:/workout
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
  lazydocker:
    build:
      context: https://github.com/jesseduffield/lazydocker.git
      args:
        BASE_IMAGE_BUILDER: golang
        GOARCH: amd64
        GOARM:
    image: lazyteam/lazydocker
    container_name: lazydocker
    stdin_open: true
    tty: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/appdata/lazydocker/config:/config
  nextcloud:
    image: lscr.io/linuxserver/nextcloud
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /opt/appdata/nextcloud/config:/config
      - /mnt/storage/nextcloud/data:/data
    depends_on:
      - mariadb
      - swag
#    ports:
#      - 444:444
    restart: unless-stopped
  mariadb:
    image: ghcr.io/linuxserver/mariadb
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=camscloudissosecureyoudontevenknow
      - TZ=Europe/London
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=camuser
      - MYSQL_PASSWORD=camscloudissosecure
    volumes:
      - /opt/appdata/mariadb:/config
    restart: unless-stopped
  gluetun:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      #test add deluge port
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
    volumes:
#      - /yourpath:/gluetun
      - /opt/appdata/gluetun:/config
    environment:
      # See https://github.com/qdm12/gluetun/wiki
      - VPNSP=mullvad
      - VPN_TYPE=openvpn
      # OpenVPN:
      - OPENVPN_USER=3428543284587563
      - OPENVPN_PASSWORD=NKHJhMNx9G8qmBa4
      - EXTRA_SUBNETS=192.168.1.0/24
      # Wireguard:
      # - WIREGUARD_PRIVATE_KEY=wOEI9rqqbDwnN8/Bpp22sVz48T71vJ4fYmFWujulwUU=
      # - WIREGUARD_ADDRESS=10.64.222.21/32
      # Timezone for accurate log times
      - TZ=Europe/London
  deluge:
    image: lscr.io/linuxserver/deluge
    network_mode: "service:gluetun"
    container_name: deluge
    environment:
      - UMASK_SET=022
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - /mnt/disk1/downloads:/downloads
#      - /mnt/storage/movies:/movies
#      - /mnt/storage/tv:/tv
      - /opt/appdata/deluge:/config
    #routing through gluetin so these ports are unnecessary
#    ports:
#      - 8112:8112
#      - 6881:6881
#      - 6881:6881/udp
#    restart: unless-stopped
  jackett:
    image: ghcr.io/linuxserver/jackett
    container_name: jackett
    environment:
#      - PUID=1000
#      - PGID=1000
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/London
      - AUTO_UPDATE=true #optional
  #    - RUN_OPTS=<run options here> #optional
    volumes:
      - /opt/appdata/jackett:/config
      - /mnt/disk1/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/appdata/radarr:/config
      - /mnt/storage/movies:/movies
      - /mnt/disk1/downloads:/downloads
#      - ${DOWNLOADS_DIR}:/data
    ports:
      - 7878:7878
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    restart:
      always
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/appdata/sonarr:/config
      - /mnt/storage/tv:/tv
      - /mnt/disk1/downloads:/downloads
#      - ${DOWNLOADS_DIR}:/data
    ports:
      - 8989:8989
#    links:
#      - nzbget
    restart: always
    environment:
#      - PUID=${PUID}
#      - PGID=${PGID}
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - URL=cconable.com
      - SUBDOMAINS=www,radarr,sonarr,nextcloud
      - VALIDATION=http
    volumes:
      - /home/aptalca/appdata/swag:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
